### ISSUE TITLE
Virus Total / Hybrid Analysis Result

### ISSUE THREAD

**Issue by antuketot76** [fireeye/GeoLogonalyzer#5]
Is this false detection by Virus Total.
Virus Total Link - [HERE](https://www.virustotal.com/#/file/9e8a8a05e25af464a1af13b6193da214260612d04bf0745cef382392c02aed75/detection)
![image](https://user-images.githubusercontent.com/33280865/40810845-07562276-656a-11e8-9c12-110c48b7366f.png)

Same goes to Hybrid Analysis.
Hybrid Analysis Link - [HERE](https://www.hybrid-analysis.com/sample/9e8a8a05e25af464a1af13b6193da214260612d04bf0745cef382392c02aed75)
![image](https://user-images.githubusercontent.com/33280865/40811400-0ae4ab40-656c-11e8-9662-3ecadebb1706.png)

![image](https://user-images.githubusercontent.com/33280865/40811176-37a8d710-656b-11e8-9fb2-1f62d090afc5.png)

**Comment by davidpany** [comment]
Thank you for sharing this. I believe that those detection sites think the GeoLogonalyzer exe file is suspicious because it is compiled with pyinstaller.
