### ISSUE TITLE
AttributeError: 'Reader' object has no attribute 'asn'

### ISSUE THREAD

**Issue by misthi1** [fireeye/GeoLogonalyzer#8]
I got this error whenever i executed command
raceback (most recent call last):
  File "GeoLogonalyzer.py", line 985, in <module>
    main(args)
  File "GeoLogonalyzer.py", line 762, in main
    asn_db_match = asn_db_reader.asn(ip_string)
AttributeError: 'Reader' object has no attribute 'asn'

**Comment by davidpany** [comment]
Hi misthi1, out of curiosity, are you running this tool on a Mac or Windows system?

**Comment by davidpany** [comment]
Hi misthi1, testing indicated that an older version of the geoip2 dependency may have caused the mmdb files to load without all available data such as the asn attribute. 

The requirements.txt file now requires geoip2>=2.9.0 and the tool checks for the recent version as well. Please report back if you still have issues.

**Comment by misthi1** [comment]
I am using windows.
